# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Default'

variables:
  PATH: 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0;E:\\maven\\apache-maven-3.8.6-bin\\apache-maven-3.8.6\\bin;$PATH'
  REPO_PATH: 'D:\\DOCKER-GCR\\3-Dec-24\\GreenCodeScan-main'
  PYTHON_PATH: 'F:\\python\\python.exe'
  PYTEST_PATH: 'F:\\python\\Scripts\\pytest.exe'
  CLIENT_NAME: 'Demo'

stages:
  - stage: TrackServerEmissions
    displayName: 'Stage 2: Track Server Emissions'
    jobs:
    - job: TrackServerEmissions
      steps:
      - script: |
          cd $(REPO_PATH)
          $(PYTHON_PATH) server_emissions.py
        continueOnError: true
  
  - stage: GreenITCodeGeneration
    displayName: 'Stage 3: Energy Efficient Code Generation'
    jobs:
    - job: GreenITCodeGeneration
      steps:
      - script: |
          cd $(REPO_PATH)
          $(PYTHON_PATH) GreenCodeRefiner.py
        continueOnError: true
        env:
          PYTEST: $(PYTEST_PATH)
  
  - stage: DynamicCodeAnalysis
    displayName: 'Stage 4: Dynamic Code Analysis'
    jobs:
    - job: DynamicCodeAnalysis
      steps:
      - script: |
          cd $(REPO_PATH)
          $(PYTHON_PATH) track_emissions.py
        continueOnError: true
        env:
          PYTEST: $(PYTEST_PATH)
